### PR TITLE
Uncomment tests that appear to perform quickly

### PR DESCRIPTION
**Pull request by ryanblock**
Testing locally, all these took <1s to run

### We really appreciate your commitment to improving Dynalite

To maintain a high standard of quality in our releases, before merging every pull request we ask that you've completed the following:

- [ ] Forked the repo and created your branch from `main`
- [ ] Made sure tests pass (run `npm it` from the repo root)
- [ ] Expanded test coverage related to your changes:
  - [ ] Added and/or updated unit tests (if appropriate)
  - [ ] Added and/or updated integration tests (if appropriate)
- [ ] Updated relevant documentation
- [ ] Summarized your changes in `changelog.md`
- [ ] Linked to any related issues, PRs, etc. below that may relate to, consume, or necessitate these changes

Please also be sure to completed the CLA (if you haven't already).

Learn more about [contributing to Architect here](https://arc.codes/intro/community).

Thanks again!

### CODE REVIEW

**Comment by mhart** [comment]
Just for some context here – they all run quickly locally – but are slow remotely, which is why they're called out.

You might just wanna run tests with `REMOTE=true` to check if these are actually fast on live/prod DynamoDB (I suspect they're not).

Not suggesting to leave them commented – just might wanna keep some sort of comments or similar so you know which ones to skip if trying to do a fast test remotely.

**Comment by ryanblock** [comment]
Ah, super helpful note! I'll going to restore these as part of a "slow" test run in a separate job against live infra.

**Comment by mhart** [comment]
Yup, sounds good – also, just in case it's a bit obscure, the `~100 runs quickly` in the comments means "setting write capacity to 100 makes this run not too horribly"

**Comment by ryanblock** [comment]
Hmm, perhaps I spoke too soon. Ran the test suite against AWS and came up with a fair number of errors, so maybe I'll pump the brakes on that for a minute until I've got some time to figure out why. Going to put those tests back under conditionals though for any future revisits.

**Pull request merged**
